name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "Helllo Git-hub_action"
      - name: Print a few Linesss
        run: | 
          echo "123"
          echo "312"
      
   
